# Step 1: OCR PDF using Mistral AI

In [ ]:
from dotenv import load_dotenv

load_dotenv("./.env")

from ocr.ocr_pdf import ocr_pdf

path = "c:/Users/natha/Zotero/storage/LR6YL5A9/Ribier - 1666 - Lettres Et Memoires D'Estat Des Roys, Princes, Amb.pdf"

name = "ribier_v1"

# md = ocr_pdf(path)
# with open(f"{name}.json", "w") as f:
#     f.write(md.model_dump_json(indent=2))

In [20]:
letters[-22]

{'title': 'LE ROY À BASSE-FONTAINE SON AMBASSADEUR.',
 'pdf_pages': [638, 639],
 'book_pages': ['617', '118'],
 'markdown': "\n*Pour solliciter le Duc de Saxe à souvenir la guerre contre l'Empereur.*\n\nMonsieur de Basse-Fontaine, je vous ay prié &amp; mandé par mes detniétés de vous en retournent par deuets le Duc de Saxe Elečteur, &amp; refider auprès de luy pour quelque temps : n'y manquez pas, jusqu's à ce que vous le voyez bien deliberé &amp; refolu à foutenir la guerre, contre l'Empereur, luy donnant toutes les perfusions à cette fin dont vous vous pouvez aduire, &amp; luy dites que je suis certainement aduerti, quelque bruit que l'Empereur faffe femer en la Germanie, que le Grand Seigneut à fon Armée preste pour fa venue cette année en Hongrie, &amp; que la course qu'auoit fait le Sophy fut les limites dudit Grand-Seigneur, luy a coufté bien cher : cat le San-jaques qui eftoit fur les confins de ce païs-là ne s'eft pas cotenté de reprendre ce que l'Armée dudit Sophy auoit dérobé; mais la techaffé bien auant dans fon païs, où il a fait grand degaft &amp; brouillement, &amp; eft affeuré que le Turc n'arteftera pour cela d'executer fon entreprise fut la Hongrie. Pareillement l'Elečteur &amp; les alliez doivent confiderer l'extrême necesité d'argent en laquelle eft ledit Empereur, &amp; qu'il n'a moyen d'en recouuter, fi ce n'eft de ceux qui voudroient acheter de luy une servitude perpetuelle, comme les Villes Imperiales, lesquelles le voyant pour cette heure sans force ny affemblée de gens composent fi honteusement auce luy, aimant mieux fe mettre à tançon pour entrer en servitude, que d'employer leurs deniers à construer &amp; perpetuer leur liberté, &amp; n'oubliez pas à louet grandement le grand cœur dudit Duc, lequel à ce que je voy, aimeroit mieux mourir que faire chose honteuse. Au reste vous m'auez fait bien grand plaifit d'auoit trouvé moyen que ledit Elečteur écriue fouuent à ceux de Strasbourg, deuets lesquels j'ay envoyé le St. de Mandoffe mon premier Maître d'Hostel : &amp; ay eu nouvelles que quelque poursuite &amp; menée qu'ait fait l'Empereur enuers eux, ils font encotes en leur entier. Et quant à ceux d'Auguste, ils ont refusé les garnisons que l'Empereur leur auoit voulu bailler, &amp; à ce que j'entends de toutes parts, il n'eft point en la puissance de l'Empereur de forcer aucunes defdites Villes, fi elles ont envie de fe defendre: &amp; messement Strasbourg qui eft bien pourueu de bons Capitaines &amp; gens de guerre, &amp; de toutes autres choses requises pour fa defenfe. Au surplus foyez affeuré que voître demeure de pat delà en acheuant ce que vous auez fi bien commencé, vous feruira de grande recommenda-\n\nIi parait que l'Ambaßadeur auoit donné aduis au Roy des déliens de l'Empereur de luy faire la guerre.\n\n111 ij118 LETTRES ET MEMOIRES D'ESTAT;\ntion enûers moy : ptiant Dieu, Monficut de Baffe - Fontaine, qu'il vous ait en fa garde. Eferit à Villepreux, le 17. Fevrier 1547.\n\n"}

In [ ]:
import polars as pl

df = pl.DataFrame(
    {
        "title": [l["title"] for l in letters],
        "pdf_pages": [l["pdf_pages"] for l in letters],
        "book_pages": [l["book_pages"] for l in letters],
        "markdown": [l["markdown"] for l in letters],
    }
)

df.with_columns(
    [
        pl.col("pdf_pages").list.eval(pl.element().cast(pl.String)).list.join(","),
        pl.col("book_pages").list.eval(pl.element().cast(pl.String)).list.join(","),
    ]
).write_csv("ribier_letters.csv")

print(df.shape)
df.head()

(343, 4)

shape: (5, 4)
┌────────────────────────────┬────────────────┬────────────────────┬───────────────────────────────┐
│ title                      ┆ pdf_pages      ┆ book_pages         ┆ markdown                      │
│ ---                        ┆ ---            ┆ ---                ┆ ---                           │
│ str                        ┆ list[i64]      ┆ list[str]          ┆ str                           │
╞════════════════════════════╪════════════════╪════════════════════╪═══════════════════════════════╡
│ CONTENANS                  ┆ [4]            ┆ []                 ┆                               │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆ LES INTELLIGENCES DE CES ROY… │
│ ET                         ┆ [4, 5, … 16]   ┆ ["10", "3", … "7"] ┆                               │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆ DANS L'ITALIE SEVLE, LES INT… │
│ SVR LA PIECE SVIVANTE,     ┆ [16]           ┆ ["3"]              ┆                               │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆                               │
│ ET AVTRES DV PREMIER LIVRE ┆ [16]           ┆ ["3"]              ┆                               │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆                               │
│ DE CE RECEVIL              ┆ [16, 17, … 24] ┆ ["3", "6", … "1"]  ┆                               │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆ ![img-6.jpeg](img-6.jpeg)     │
│                            ┆                ┆                    ┆                               │
│                            ┆                ┆                    ┆ E…                            │
└────────────────────────────┴────────────────┴────────────────────┴───────────────────────────────┘

In [23]:
df.sample(10)

shape: (10, 4)
┌──────────────────────────┬───────────────────┬─────────────────────────┬─────────────────────────┐
│ title                    ┆ pdf_pages         ┆ book_pages              ┆ markdown                │
│ ---                      ┆ ---               ┆ ---                     ┆ ---                     │
│ str                      ┆ list[i64]         ┆ list[str]               ┆ str                     │
╞══════════════════════════╪═══════════════════╪═════════════════════════╪═════════════════════════╡
│ AV CONNESTABLE.          ┆ [459, 460, 461]   ┆ ["417", "418", "439"]   ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ De l'armement           │
│                          ┆                   ┆                         ┆ extraordinaire…         │
│ AV CONNESTABLE.          ┆ [527, 528, … 530] ┆ ["53", "306", … "508"]  ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ De la deputation des    │
│                          ┆                   ┆                         ┆ Princes…                │
│ AV ROY.                  ┆ [497, 498, 499]   ┆ ["475", "476", "477"]   ┆                         │
│                          ┆                   ┆                         ┆ Le Pape reconnoit que   │
│                          ┆                   ┆                         ┆ la Chre…                │
│ ESCRIT DE L'EMPEREUR     ┆ [388, 389, 390]   ┆ ["365", "366", "367"]   ┆ touchant son intention  │
│ CHARLES-Q…               ┆                   ┆                         ┆ avec ce…                │
│ L’Autre originale que    ┆ [240, 241, … 245] ┆ ["217", "118", … "222"] ┆                         │
│ l’ay, po…                ┆                   ┆                         ┆ E e118 LETTRES ET       │
│                          ┆                   ┆                         ┆ MEMOIRES D'…            │
│ LETTRE DU RÔT DE SVEDE   ┆ [591, 592]        ┆ ["370", "571"]          ┆                         │
│ AV ROY                   ┆                   ┆                         ┆ *François I.*           │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ En fuite d'one…         │
│ Origin.                  ┆ [563, 564, … 568] ┆ ["142", "543", … "547"] ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ ILLVSTRIS Domine        │
│                          ┆                   ┆                         ┆ Cæfarem vel…            │
│ AV CONNESTABLE.          ┆ [443, 444]        ┆ ["421"]                 ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ Que la ligue du Pape,   │
│                          ┆                   ┆                         ┆ de l'E…                 │
│ AV CONNESTABLE.          ┆ [515]             ┆ ["423"]                 ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ Touchant le Vaisseur    │
│                          ┆                   ┆                         ┆ pour le…                │
│ Origin.                  ┆ [661, 662, … 665] ┆ ["40", "641", … "3"]    ┆                         │
│                          ┆                   ┆                         ┆                         │
│                          ┆                   ┆                         ┆ On n'ausit pas encore   │
│                          ┆                   ┆                         ┆ nouvel…                 │
└──────────────────────────┴───────────────────┴─────────────────────────┴─────────────────────────┘

In [24]:
df["markdown"].str.split(" ").list.len().mean()

1031.0

In [26]:
df.write_parquet("ribier_letters.parquet")